// theme definitions

// TODO: define dark theme
export const dark = rawTheme => ({
  ...rawTheme,

  COLOR_BG_PRIMARY: rawTheme.COLOR_WHITE,
  COLOR_BG_SECONDARY: rawTheme.COLOR_LIGHT_GRAY,
  COLOR_BG_INVERT: rawTheme.COLOR_BLACK,

  COLOR_TEXT_PRIMARY: rawTheme.COLOR_BLACK,
  COLOR_TEXT_SECONDARY: rawTheme.COLOR_DARK_GRAY,
  COLOR_TEXT_INVERT_HIGHLIGHT: rawTheme.COLOR_WHITE,
  COLOR_TEXT_INVERT_PRIMARY: rawTheme.COLOR_GRAY,
  COLOR_TEXT_INVERT_SECONDARY: rawTheme.COLOR_DARK_GRAY,
  COLOR_TEXT_ACTIVE: rawTheme.COLOR_BLUE,
  COLOR_TEXT_INACTIVE: rawTheme.COLOR_GRAY,

  COLOR_BORDER_ACTIVE: rawTheme.COLOR_DARK_GRAY,
  COLOR_BORDER_PRIMARY: rawTheme.COLOR_GRAY,
  COLOR_BORDER_SECONDARY: rawTheme.COLOR_DIM_GRAY,
  COLOR_BORDER_OPTIONAL: rawTheme.COLOR_LIGHT_GRAY,
});

export const light = rawTheme => ({
  ...rawTheme,

  COLOR_BG_PRIMARY: rawTheme.COLOR_WHITE,
  COLOR_BG_SECONDARY: rawTheme.COLOR_LIGHT_GRAY,
  COLOR_BG_INVERT: rawTheme.COLOR_BLACK,

  COLOR_TEXT_PRIMARY: rawTheme.COLOR_BLACK,
  COLOR_TEXT_SECONDARY: rawTheme.COLOR_DARK_GRAY,
  COLOR_TEXT_INVERT_HIGHLIGHT: rawTheme.COLOR_WHITE,
  COLOR_TEXT_INVERT_PRIMARY: rawTheme.COLOR_GRAY,
  COLOR_TEXT_INVERT_SECONDARY: rawTheme.COLOR_DARK_GRAY,
  COLOR_TEXT_ACTIVE: rawTheme.COLOR_BLUE,
  COLOR_TEXT_INACTIVE: rawTheme.COLOR_GRAY,

  COLOR_BORDER_ACTIVE: rawTheme.COLOR_DARK_GRAY,
  COLOR_BORDER_PRIMARY: rawTheme.COLOR_GRAY,
  COLOR_BORDER_SECONDARY: rawTheme.COLOR_DIM_GRAY,
  COLOR_BORDER_OPTIONAL: rawTheme.COLOR_DIM_GRAY,
});

